# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Browser Build

on:
  push:
    branches: [main, production]
  pull_request:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: mkdir -p browser-artifact
      - run: npm run build:ga
        env:
          GOOGLE_CLIENT_ID_DEV: ${{ secrets.GOOGLE_CLIENT_ID_DEV }}
          GOOGLE_CLIENT_ID_PROD: ${{ secrets.GOOGLE_CLIENT_ID_PROD }}
          GOOGLE_ANALYTICS_ID: ${{ secrets.GOOGLE_ANALYTICS_ID }}
      - run: mv dist browser-artifact/ga
      - run: npm run build:fs
        env:
          GOOGLE_ANALYTICS_ID: ${{ secrets.GOOGLE_ANALYTICS_ID }}
      - run: mv dist browser-artifact/fs
      - name: Upload Browser Artifact
        if: github.ref == 'refs/heads/production'
        uses: actions/upload-artifact@v4
        with:
          name: tinycad-browser
          path: browser-artifact
          if-no-files-found: error
      - name: Upload Pages Artifact
        if: github.event_name == 'push' && github.ref == 'refs/heads/production'
        uses: actions/upload-pages-artifact@v3
        with:
          path: browser-artifact

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/production'
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
